language: ruby # don't install any environment
sudo: false

script: ./cibuild.sh

env:
  global:
  - ENCRYPTION_LABEL: "afff9a76cc1e"
  - COMMIT_AUTHOR_EMAIL: "travis.build@allover.earth"
rvm:
  - 2.3.3