# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: All Over Earth
  th: All Over Earth
author: Brandon & Gam
author_link: https://allover.earth
author_description:
  en: Just another couple with a travel blog
  th: Just another couple with a travel blog
email: hi@allover.earth
description:
  en: Brandon and Gam are travelling around the Earth. We're documenting what we find, so stay tuned.
  th: แบรนดอน แอนด์ แก้ม (เมกันผิวขาวและคนไทยผิวแทน) ผู้ที่จะเดินทางรอบโลก และพวกเราจะบันทึกทุกสิ่งที่พวกเราเจอไว้ที่นี่ โปรดติดตาม!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://allover.earth" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id:

# Build settings
gems:
  - jekyll-paginate
  - jekyll-polyglot
markdown: kramdown
permalink: pretty

# Pagination
paginate: 4
# Sass
sass:
    style: :compressed

languages: ["en", "th"]
# site.languages_friendly should match the order of site.languages
#   and is used to display languages in friendly terms (such as in the
#   language selector)
languages_friendly: ["eng", "thai"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# for travis compatibility.  see: https://jekyllrb.com/docs/continuous-integration/travis-ci/
exclude: [vendor]
